# Fully Vectorized K-Mer Counting

In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('dark_background')

In [2]:
from SeqRep.dataset_builder import DatasetBuilder, SILVAHeaderParser
builder = DatasetBuilder(SILVAHeaderParser())
dataset = builder.from_fasta(['SILVA_138.1_SSURef_NR99_tax_silva.fasta'])

In [141]:
from SeqRep.kmers import KMerCounter

counter = KMerCounter(2, jobs=7, chunksize=1000)
counter.kmer_counts(dataset['seqs'].to_numpy())

Generating kmer sequences...








  0%|          | 0/510508 [00:00<?, ?it/s]





  0%|          | 1/510508 [00:04<652:41:06,  4.60s/it]





  2%|▏         | 8001/510508 [00:04<03:29, 2400.37it/s]





  3%|▎         | 13001/510508 [00:04<01:54, 4334.23it/s]





  4%|▎         | 19001/510508 [00:04<01:07, 7320.90it/s]





  5%|▍         | 25001/510508 [00:05<00:43, 11034.80it/s]





  6%|▌         | 31001/510508 [00:05<00:30, 15508.82it/s]





  7%|▋         | 36148/510508 [00:05<00:24, 19559.49it/s]





  8%|▊         | 42001/510508 [00:05<00:18, 24749.55it/s]





  9%|▉         | 47140/510508 [00:05<00:16, 28955.08it/s]





 10%|█         | 53001/510508 [00:05<00:13, 33447.84it/s]





 12%|█▏        | 59001/510508 [00:05<00:11, 38464.45it/s]





 13%|█▎        | 64215/510508 [00:05<00:10, 41466.19it/s]





 14%|█▎        | 69412/510508 [00:05<00:10, 43959.26it/s]





 15%|█▍        | 75001/510508 [00:06<00:09, 44870.18it/s]





 16%|█▌        | 81001/510508 [00:06<00:09, 45764.87it/s]





 17%|█▋ 

Counting unique kmers...








  0%|          | 0/510508 [00:00<?, ?it/s]





  0%|          | 1/510508 [00:03<479:19:30,  3.38s/it]





  3%|▎         | 13001/510508 [00:03<01:34, 5267.34it/s]





  5%|▍         | 23001/510508 [00:03<00:46, 10448.62it/s]





  7%|▋         | 35001/510508 [00:03<00:26, 18246.68it/s]





  9%|▉         | 46001/510508 [00:03<00:17, 26514.93it/s]





 11%|█         | 55634/510508 [00:03<00:13, 33638.24it/s]





 13%|█▎        | 64600/510508 [00:04<00:10, 40757.62it/s]





 14%|█▍        | 74001/510508 [00:04<00:08, 48790.50it/s]





 16%|█▌        | 82663/510508 [00:04<00:07, 55778.87it/s]





 18%|█▊        | 91301/510508 [00:04<00:06, 60838.84it/s]





 20%|█▉        | 100001/510508 [00:04<00:06, 66556.20it/s]





 22%|██▏       | 110001/510508 [00:04<00:05, 74413.66it/s]





 23%|██▎       | 118860/510508 [00:04<00:05, 78057.25it/s]





 25%|██▌       | 127717/510508 [00:04<00:04, 77853.24it/s]





 27%|██▋       | 136236/510508 [00:04<00:04, 79772.22it/s]







[array([125,  85, 121, 123,  91,  84,  90, 105, 133, 101, 143, 109, 105,
        100, 132, 143]),
 array([104,  97, 116,  69,  88,  77, 100,  82, 114, 107, 154, 110,  80,
         66, 115,  58]),
 array([122,  89, 116, 116,  90,  92, 110, 101, 133, 108, 150, 100,  97,
        104, 116, 123]),
 array([121, 101, 129,  73,  92,  98, 117,  89, 133, 128, 184, 107,  77,
         69, 122,  65]),
 array([136,  90, 111, 113,  82,  75,  97,  96, 126,  91, 136, 107, 106,
         95, 116, 149]),
 array([ 75,  74,  81,  53,  61,  62, 114,  67,  91, 110, 170,  93,  57,
         58,  98,  48]),
 array([105,  79, 108,  67,  69,  63,  86,  68, 100,  92, 113,  92,  85,
         52,  90,  62]),
 array([111,  94, 119,  67,  80,  78,  98,  78, 112, 101, 136, 105,  88,
         61, 102,  65]),
 array([112,  91, 112, 108,  84,  98, 105, 112, 128, 109, 157, 107,  98,
        101, 127, 118]),
 array([137,  89, 122, 134,  99,  75,  85,  97, 140,  93, 133, 111, 106,
         99, 137, 150]),
 array([131,  89, 12